# Generated by Django 6.0.7 on 2026-07-23 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bid_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
